apiVersion: apps/v1 
kind: Deployment
metadata:
  name: myapp-deploment
  labels:
    app : myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
         app: myapp
         type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always

  replicas: 3
  selector:
    matchLabels:
      type: front-end
